### ISSUE TITLE
Code not working for long addresses

### ISSUE THREAD

**Issue by dpalic** [ogun/uule_grabber#2]
here a canonical name
BURGERHEIM, Bischöflich-Geistlicher-Rat-Josef-Zinnbauer-Straße 8, 84130 Dingolfing, Germany

this is not working at all

**Comment by pouria-ariafar** [comment]
I have the same problem and it causes the conversion error
I wish this library was as accurate as the following tool:
https://site-analyzer.pro/services-seo/uule/

Sample:
uule_grabber: w+CAIQICI**b**2KfYtdmB2YfYp9mG2Iwg2KfYs9iq2KfZhiDYp9i12YHZh9in2YbYjCDYp9uM2LHYp9mG
site-analyzer.pro: w+CAIQICI**z**2KfYtdmB2YfYp9mG2Iwg2KfYs9iq2KfZhiDYp9i12YHZh9in2YbYjCDYp9uM2LHYp9mG

The difference between these two is in z and b and it does not work for uule_grabber.

**Comment by ogun** [comment]
I'm sorry for not getting back to you sooner @dpalic @baharmf93. I fixed the problem and will update the package. Thanks for the heads up.

**Comment by pouria-ariafar** [comment]
Thank you for paying attention @ogun .
Your code has improved but this is still the case in some addresses, for example, I have an address from the UAE and it has exactly the above problem.
aaddress = 'مدينة زايد, منطقة الظفرة, أبو ظبي, الإمارات العربية المتحدة'
uule_grabber:
w+CAIQIC**I**r2YXYr9mK2YbYqSDYstin2YrYrywg2YXZhti32YLYqSDYp9mE2LjZgdix2KksINij2KjZiCDYuNio2YosINin2YTYpdmF2KfYsdin2Kog2KfZhNi52LHYqNmK2Kkg2KfZhNmF2KrYrdiv2Kk
correct uule:
w+CAIQIC**J**r2YXYr9mK2YbYqSDYstin2YrYrywg2YXZhti32YLYqSDYp9mE2LjZgdix2KksINij2KjZiCDYuNio2YosINin2YTYpdmF2KfYsdin2Kog2KfZhNi52LHYqNmK2Kkg2KfZhNmF2KrYrdiv2Kk
The only difference is in its ninth letter. The first one is I, but the second one, which is correct, is J.

**Comment by ogun** [comment]
Hello @SardarDelha, 

Sorry for the problem, let me check it and come back to you.

**Comment by ogun** [comment]
@SardarDelha The first letters in UULE should be constant and they should be `w+CAIQICI`

I've also checked your example with https://site-analyzer.pro/services-seo/uule/ and it also produced the same result. How did you find the correct UULE?

**Comment by pouria-ariafar** [comment]
I found [the address](https://valentin.app/uule.html) with the help of this. I found the address with the help of this. This site is more accurate.
[Google result with correct uule](https://www.google.nl/search?q=where%20am%20i&gl=us&hl=en&uule=w+CAIQICJr2YXYr9mK2YbYqSDYstin2YrYrywg2YXZhti32YLYqSDYp9mE2LjZgdix2KksINij2KjZiCDYuNio2YosINin2YTYpdmF2KfYsdin2Kog2KfZhNi52LHYqNmK2Kkg2KfZhNmF2KrYrdiv2Kk&num=10&pws=0)
And if we search uule_grabber in Google, [the location will be unknonw](https://www.google.nl/search?q=where%20am%20i&gl=us&hl=en&uule=w+CAIQICIr2YXYr9mK2YbYqSDYstin2YrYrywg2YXZhti32YLYqSDYp9mE2LjZgdix2KksINij2KjZiCDYuNio2YosINin2YTYpdmF2KfYsdin2Kog2KfZhNi52LHYqNmK2Kkg2KfZhNmF2KrYrdiv2Kk&num=10&pws=0), the [site-analyzer.pro site](https://site-analyzer.pro/services-seo/uule/) also has this error.
Unfortunately, I don't know how it was calculated, but I think `w+CAIQIC` is always a fixed value and `I` may change.

**Comment by ogun** [comment]
Let me try to understand it. If I can solve it, I will update here.

**Comment by ogun** [comment]
Hello again @SardarDelha,

I've released the new version (v0.1.8) now. Please feel free to check it, your issue should be fixed. Thank you for the source btw. I will also implement UULE v2 in the upcoming days.

Have a nice day!
